name: publish KPMG.TaxConnect.Template.FuncServiceBus to nuget
on:
  push:
    branches:
      - main # Your default release branch
    paths:
      - 'KPMG.TaxConnect.Template.FuncServiceBus.nuspec'
jobs:
  publish:
    name: list on nuget
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
          
      - name: Package the template
        run: nuget pack KPMG.TaxConnect.Template.FuncServiceBus.nuspec -NoDefaultExcludes
        
      - name: Publish to nuget.org
        run: nuget push KPMG.TaxConnect.Template.FuncServiceBus.*.nupkg -src https://pkgs.dev.azure.com/KPMG-UK/8bacc871-4855-4450-9cdf-1bcc470589ff/_packaging/taxconnect/nuget/v3/index.json ${{secrets.NUGET_API_KEY}}
